package github

import (
	"fmt"
	"strings"
	"time"

	"github.com/p-n-ai/oss-bot/internal/parser"
)

// PRRequest holds all data needed to create a pull request.
type PRRequest struct {
	Owner      string
	Repo       string
	Title      string
	Body       string
	BranchName string
	BaseBranch string
	Files      []FileChange
	Labels     []string
	Reviewers  []string
}

// FileChange represents a file to be created or updated in a PR.
type FileChange struct {
	Path    string
	Content string
}

// PRResult holds the result of creating a pull request.
type PRResult struct {
	Number int
	URL    string
	Branch string
}

// GenerateBranchName creates a consistent, URL-safe branch name for bot-created PRs.
// Format: oss-bot/<action>-<content-type>-<topic-id>-<timestamp>
func GenerateBranchName(action, contentType, topicID string) string {
	timestamp := time.Now().Format("20060102-150405")
	r := strings.NewReplacer("/", "-", " ", "-")
	return fmt.Sprintf("oss-bot/%s-%s-%s-%s",
		action,
		r.Replace(contentType),
		r.Replace(topicID),
		timestamp,
	)
}

// BuildPRBody creates the PR description with provenance metadata and a review checklist.
func BuildPRBody(cmd parser.BotCommand, model string, generatedAt time.Time) string {
	var sb strings.Builder

	sb.WriteString("## Auto-generated by OSS Bot\n\n")
	sb.WriteString(fmt.Sprintf("**Requested by:** @%s\n", cmd.User))
	sb.WriteString(fmt.Sprintf("**Command:** `@oss-bot %s`\n", cmd.Action))
	sb.WriteString(fmt.Sprintf("**Topic:** `%s`\n", cmd.TopicPath))
	sb.WriteString(fmt.Sprintf("**Model:** %s\n", model))
	sb.WriteString(fmt.Sprintf("**Generated at:** %s\n\n", generatedAt.Format(time.RFC3339)))

	sb.WriteString("### Provenance\n")
	sb.WriteString("```yaml\n")
	sb.WriteString("provenance: ai-generated\n")
	sb.WriteString(fmt.Sprintf("model: %s\n", model))
	sb.WriteString("generator: oss-bot\n")
	sb.WriteString(fmt.Sprintf("generated_at: %q\n", generatedAt.Format(time.RFC3339)))
	sb.WriteString("```\n\n")

	sb.WriteString("### Review Checklist\n")
	sb.WriteString("- [ ] Content is pedagogically sound\n")
	sb.WriteString("- [ ] Mathematical notation is correct\n")
	sb.WriteString("- [ ] Curriculum terminology is accurate\n")
	sb.WriteString("- [ ] Passes schema validation\n")

	return sb.String()
}
