package github_test

import (
	"strings"
	"testing"
	"time"

	gh "github.com/p-n-ai/oss-bot/internal/github"
	"github.com/p-n-ai/oss-bot/internal/parser"
)

func TestGenerateBranchName(t *testing.T) {
	tests := []struct {
		name        string
		action      string
		contentType string
		topicID     string
	}{
		{"basic", "add", "teaching-notes", "algebra-01"},
		{"topic with slash", "add", "assessments", "math/algebra/01"},
		{"content type with space", "add", "teaching notes", "f1-01"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := gh.GenerateBranchName(tt.action, tt.contentType, tt.topicID)
			if got == "" {
				t.Error("GenerateBranchName() returned empty string")
			}
			if len(got) > 255 {
				t.Errorf("branch name too long: %d chars", len(got))
			}
			if !strings.HasPrefix(got, "oss-bot/") {
				t.Errorf("branch name should start with oss-bot/, got %q", got)
			}
			if strings.Contains(got, " ") {
				t.Error("branch name must not contain spaces")
			}
		})
	}
}

func TestBuildPRBody(t *testing.T) {
	cmd := parser.BotCommand{
		Action:    "add",
		TopicPath: "algebra/01-linear-equations",
		User:      "testuser",
	}
	at := time.Date(2026, 3, 27, 0, 0, 0, 0, time.UTC)

	body := gh.BuildPRBody(cmd, "gpt-4o", at)

	checks := []string{
		"Auto-generated by OSS Bot",
		"@testuser",
		"algebra/01-linear-equations",
		"gpt-4o",
		"provenance: ai-generated",
		"Review Checklist",
	}
	for _, want := range checks {
		if !strings.Contains(body, want) {
			t.Errorf("BuildPRBody() missing %q", want)
		}
	}
}

func TestPRRequest_Fields(t *testing.T) {
	pr := gh.PRRequest{
		Owner:      "p-n-ai",
		Repo:       "oss",
		Title:      "Add teaching notes for F1-01",
		Body:       "Generated by oss-bot",
		BranchName: gh.GenerateBranchName("add", "teaching-notes", "F1-01"),
		BaseBranch: "main",
		Files: []gh.FileChange{
			{Path: "topics/algebra/01.teaching.md", Content: "# Notes"},
		},
		Labels: []string{"provenance:ai-generated"},
	}

	if pr.Owner == "" || pr.Repo == "" {
		t.Error("PR request must have owner and repo")
	}
	if len(pr.Files) == 0 {
		t.Error("PR request must have at least one file")
	}
	if pr.BranchName == "" {
		t.Error("PR request must have a branch name")
	}
	if pr.BaseBranch == "" {
		t.Error("PR request must have a base branch")
	}
}
