package output

import (
	"context"
	"fmt"
	"strings"
	"time"

	gh "github.com/p-n-ai/oss-bot/internal/github"
)

// GitHubWriter creates PRs via the GitHub API. Used by Bot and Web Portal.
type GitHubWriter struct {
	App       *gh.App
	RepoOwner string
	RepoName  string
}

// NewGitHubWriter creates a writer that creates PRs via the GitHub API.
func NewGitHubWriter(app *gh.App, owner, repo string) *GitHubWriter {
	return &GitHubWriter{App: app, RepoOwner: owner, RepoName: repo}
}

func (w *GitHubWriter) WriteFiles(_ context.Context, _ string, _ map[string]string) error {
	return fmt.Errorf("GitHubWriter does not support local file writing — use LocalWriter")
}

// CreatePR creates a branch, commits files, and opens a pull request.
// Flow: get token → get main SHA → create branch → commit each file → open PR.
func (w *GitHubWriter) CreatePR(ctx context.Context, input PRInput) (*PROutput, error) {
	token, err := w.App.InstallationToken(ctx, w.RepoOwner+"/"+w.RepoName)
	if err != nil {
		return nil, fmt.Errorf("getting installation token: %w", err)
	}

	client := gh.NewClient(token, w.RepoOwner, w.RepoName)

	sha, err := client.GetRef(ctx, "heads/main")
	if err != nil {
		return nil, fmt.Errorf("getting main branch SHA: %w", err)
	}

	branch := gh.GenerateBranchName("add", input.ContentType, input.TopicPath)
	if err := client.CreateRef(ctx, "refs/heads/"+branch, sha); err != nil {
		return nil, fmt.Errorf("creating branch %s: %w", branch, err)
	}

	for path, content := range input.Files {
		msg := fmt.Sprintf("Add %s for %s [oss-bot]", input.ContentType, input.TopicPath)
		if err := client.PutContents(ctx, path, msg, content, branch); err != nil {
			return nil, fmt.Errorf("committing %s: %w", path, err)
		}
	}

	title := fmt.Sprintf("Add %s for %s", input.ContentType, input.TopicPath)
	body := buildPRBody(input)
	num, url, err := client.CreatePull(ctx, title, body, branch, "main", []string{"provenance:ai-generated"})
	if err != nil {
		return nil, fmt.Errorf("creating PR: %w", err)
	}
	return &PROutput{Number: num, URL: url, Branch: branch}, nil
}

// buildPRBody generates the PR description with provenance metadata and review checklist.
func buildPRBody(input PRInput) string {
	var sb strings.Builder
	sb.WriteString("## Auto-generated by OSS Bot\n\n")
	sb.WriteString(fmt.Sprintf("**Topic:** `%s`\n", input.TopicPath))
	sb.WriteString(fmt.Sprintf("**Content type:** %s\n", input.ContentType))
	sb.WriteString(fmt.Sprintf("**Source:** %s\n", input.Source))
	sb.WriteString(fmt.Sprintf("**Generated at:** %s\n\n", time.Now().UTC().Format(time.RFC3339)))

	sb.WriteString("### Provenance\n```yaml\nprovenance: ai-generated\ngenerator: oss-bot\n```\n\n")

	if input.MergeDetails != "" {
		sb.WriteString("### Merge Summary\n")
		sb.WriteString(input.MergeDetails)
		sb.WriteString("\n\n")
	}

	sb.WriteString("### Review Checklist\n")
	sb.WriteString("- [ ] Content is pedagogically sound\n")
	sb.WriteString("- [ ] Mathematical notation is correct\n")
	sb.WriteString("- [ ] Curriculum terminology is accurate\n")
	sb.WriteString("- [ ] Passes schema validation\n")

	return sb.String()
}
