package generator

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/p-n-ai/oss-bot/internal/ai"
)

// ScaffoldRequest is the input for scaffolding new curriculum structures.
type ScaffoldRequest struct {
	// SyllabusID is the unique identifier for the new syllabus (e.g. "india-jee").
	SyllabusID string
	// SubjectID is the grade-less subject identifier (e.g. "india-jee-mathematics").
	// For ScaffoldSubject, this is the parent folder under the syllabus.
	SubjectID string
	// SubjectGradeID is the full subject+grade identifier (e.g. "india-jee-mathematics-class-11").
	// This is the subfolder under SubjectID that contains topics.
	// If empty during ScaffoldSubject, it is derived from SubjectID + grade.
	SubjectGradeID string
	// SourceText is the pre-extracted content from a document, URL, or text input.
	SourceText string
	// OutputDir is the root directory to write scaffolded files into.
	OutputDir string
	// Country is used to build the directory path curricula/{country}/{syllabus_id}.
	Country string
}

// ScaffoldResult holds the files generated by the scaffolder.
type ScaffoldResult struct {
	// Files maps repo-relative paths to YAML content.
	Files map[string]string
	// Summary describes what was scaffolded.
	Summary string
}

// SyllabusYAML is a minimal syllabus descriptor.
type SyllabusYAML struct {
	ID          string   `yaml:"id"`
	Name        string   `yaml:"name"`
	NameEn      string   `yaml:"name_en"`
	CountryID   string   `yaml:"country_id"`
	Language    string   `yaml:"language"`
	Description string   `yaml:"description"`
	Subjects    []string `yaml:"subjects"`
	Provenance  string   `yaml:"provenance"`
	GeneratedAt string   `yaml:"generated_at"`
}

// Scaffolder generates new curriculum directory structures from source content.
type Scaffolder struct {
	aiProvider ai.Provider
}

// NewScaffolder creates a new Scaffolder backed by the given AI provider.
func NewScaffolder(provider ai.Provider) *Scaffolder {
	return &Scaffolder{aiProvider: provider}
}

// ScaffoldSyllabus creates a new syllabus directory with a syllabus.yaml stub.
// The AI extracts the curriculum name, subjects, and description from SourceText.
func (s *Scaffolder) ScaffoldSyllabus(ctx context.Context, req ScaffoldRequest) (*ScaffoldResult, error) {
	if req.SyllabusID == "" {
		return nil, fmt.Errorf("SyllabusID is required")
	}

	name, description, subjects, err := s.extractSyllabusInfo(ctx, req)
	if err != nil {
		// Fall back to minimal stub on AI failure
		name = req.SyllabusID
		description = "Auto-generated syllabus"
		subjects = []string{}
	}

	country := req.Country
	if country == "" {
		country = "unknown"
	}

	syllabusYAML := buildSyllabusYAML(req.SyllabusID, name, name, country, description, subjects)

	syllabusPath := filepath.Join("curricula", country, req.SyllabusID, "syllabus.yaml")
	files := map[string]string{syllabusPath: syllabusYAML}

	// Generate subject directory stubs.
	// Subject ID = {syllabus_id}-{subject_slug} (grade-less) so the folder name equals the full subject ID.
	for _, subject := range subjects {
		subjectID := req.SyllabusID + "-" + toSlug(subject)
		subjectPath := filepath.Join("curricula", country, req.SyllabusID, subjectID, "subject.yaml")
		files[subjectPath] = buildSubjectYAML(subjectID, subject, subject, req.SyllabusID, country)
	}

	return &ScaffoldResult{
		Files:   files,
		Summary: fmt.Sprintf("Scaffolded syllabus %q with %d subjects", req.SyllabusID, len(subjects)),
	}, nil
}

// ScaffoldSubject creates a new subject + subject_grade directory within an existing syllabus.
// The directory structure is: {subject_id}/subject.yaml + {subject_id}/{subject_grade_id}/subject-grade.yaml + topics/
func (s *Scaffolder) ScaffoldSubject(ctx context.Context, req ScaffoldRequest) (*ScaffoldResult, error) {
	if req.SyllabusID == "" {
		return nil, fmt.Errorf("SyllabusID is required")
	}
	if req.SubjectID == "" {
		return nil, fmt.Errorf("SubjectID is required")
	}

	country := req.Country
	if country == "" {
		country = "unknown"
	}

	// Determine subject_grade_id: use explicit value or fall back to SubjectID (for grade-less syllabi).
	subjectGradeID := req.SubjectGradeID
	if subjectGradeID == "" {
		subjectGradeID = req.SubjectID
	}

	lang := countryLanguage(country)

	// Extract subject info from source text via AI.
	// The AI returns the full name with grade (e.g. "Matematik Tingkatan 4").
	fullName, topics, err := s.extractSubjectInfo(ctx, req)
	if err != nil {
		fullName = req.SubjectID
		topics = []string{}
	}

	// Derive grade-less subject name (e.g. "Matematik Tingkatan 4" → "Matematik").
	subjectName := StripGradeFromName(fullName)
	subjectGradeName := fullName

	// Translate names to English when the MOE language is not English.
	subjectNameEn := s.translateToEnglish(ctx, subjectName, lang)
	subjectGradeNameEn := s.translateToEnglish(ctx, subjectGradeName, lang)
	topicNamesEn := s.translateTopicNames(ctx, topics, lang)

	files := map[string]string{}

	// subject.yaml — lives in the grade-less subject folder
	subjectPath := filepath.Join("curricula", country, req.SyllabusID, req.SubjectID, "subject.yaml")
	files[subjectPath] = buildSubjectYAML(req.SubjectID, subjectName, subjectNameEn, req.SyllabusID, country)

	// subject-grade.yaml — lives in the subject_grade subfolder
	subjectGradePath := filepath.Join("curricula", country, req.SyllabusID, req.SubjectID, subjectGradeID, "subject-grade.yaml")
	files[subjectGradePath] = buildSubjectGradeYAML(subjectGradeID, subjectGradeName, subjectGradeNameEn, req.SubjectID, req.SyllabusID, country)

	// topic stubs — topic ID uses the English-derived prefix + grade number
	prefix := subjectPrefix(subjectName)
	gradeNum := gradeNumberFromSubjectID(subjectGradeID)
	for i, topic := range topics {
		topicID := fmt.Sprintf("%s%s-%02d", prefix, gradeNum, i+1)
		topicNameEn := topic // fallback
		if i < len(topicNamesEn) {
			topicNameEn = topicNamesEn[i]
		}
		topicPath := filepath.Join("curricula", country, req.SyllabusID, req.SubjectID, subjectGradeID, "topics", topicID+".yaml")
		files[topicPath] = buildTopicStubYAML(topicID, topic, topicNameEn, subjectGradeID, req.SubjectID, req.SyllabusID, country)
	}

	return &ScaffoldResult{
		Files:   files,
		Summary: fmt.Sprintf("Scaffolded subject %q grade %q with %d topic stubs", req.SubjectID, subjectGradeID, len(topics)),
	}, nil
}

// WriteFiles writes all scaffolded files to the output directory.
func (s *Scaffolder) WriteFiles(result *ScaffoldResult, outputDir string) error {
	for relPath, content := range result.Files {
		full := filepath.Join(outputDir, relPath)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", relPath, err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", relPath, err)
		}
	}
	return nil
}

func (s *Scaffolder) extractSyllabusInfo(ctx context.Context, req ScaffoldRequest) (name, description string, subjects []string, err error) {
	if s.aiProvider == nil || req.SourceText == "" {
		return req.SyllabusID, "", nil, fmt.Errorf("no AI provider or source text")
	}

	prompt := fmt.Sprintf(
		"From the following curriculum document, extract:\n"+
			"1. The official name of the syllabus/curriculum\n"+
			"2. A one-sentence description\n"+
			"3. A list of subject names (one per line)\n\n"+
			"Syllabus ID: %s\n\nDocument:\n%s\n\n"+
			"Respond in this exact format:\n"+
			"NAME: <name>\nDESCRIPTION: <description>\nSUBJECTS:\n- <subject1>\n- <subject2>",
		req.SyllabusID, req.SourceText,
	)

	resp, err := s.aiProvider.Complete(ctx, ai.CompletionRequest{
		Messages: []ai.Message{{Role: "user", Content: prompt}},
	})
	if err != nil {
		return req.SyllabusID, "", nil, err
	}

	return parseSyllabusAIResponse(resp.Content, req.SyllabusID)
}

func (s *Scaffolder) extractSubjectInfo(ctx context.Context, req ScaffoldRequest) (name string, topics []string, err error) {
	if s.aiProvider == nil || req.SourceText == "" {
		return req.SubjectID, nil, fmt.Errorf("no AI provider or source text")
	}

	prompt := fmt.Sprintf(
		"From the following curriculum document, extract:\n"+
			"1. The official subject name (the full name including grade/form/class level)\n"+
			"2. A list of topic/chapter names (one per line, max 20)\n\n"+
			"Subject ID: %s\nSyllabus ID: %s\n\nDocument:\n%s\n\n"+
			"Respond in this exact format:\n"+
			"NAME: <subject name with grade, e.g. Matematik Tingkatan 4>\nTOPICS:\n- <topic1>\n- <topic2>",
		req.SubjectID, req.SyllabusID, req.SourceText,
	)

	resp, err := s.aiProvider.Complete(ctx, ai.CompletionRequest{
		Messages: []ai.Message{{Role: "user", Content: prompt}},
	})
	if err != nil {
		return req.SubjectID, nil, err
	}

	return parseSubjectAIResponse(resp.Content, req.SubjectID)
}

// parseSyllabusAIResponse parses the structured AI response for syllabus info.
func parseSyllabusAIResponse(response, fallbackID string) (name, description string, subjects []string, err error) {
	name = fallbackID
	lines := strings.Split(response, "\n")
	inSubjects := false
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "NAME:") {
			name = strings.TrimSpace(strings.TrimPrefix(line, "NAME:"))
		} else if strings.HasPrefix(line, "DESCRIPTION:") {
			description = strings.TrimSpace(strings.TrimPrefix(line, "DESCRIPTION:"))
		} else if line == "SUBJECTS:" {
			inSubjects = true
		} else if inSubjects && strings.HasPrefix(line, "- ") {
			subjects = append(subjects, strings.TrimPrefix(line, "- "))
		}
	}
	return name, description, subjects, nil
}

// parseSubjectAIResponse parses the structured AI response for subject info.
func parseSubjectAIResponse(response, fallbackID string) (name string, topics []string, err error) {
	name = fallbackID
	lines := strings.Split(response, "\n")
	inTopics := false
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "NAME:") {
			name = strings.TrimSpace(strings.TrimPrefix(line, "NAME:"))
		} else if line == "TOPICS:" {
			inTopics = true
		} else if inTopics && strings.HasPrefix(line, "- ") {
			topics = append(topics, strings.TrimPrefix(line, "- "))
		}
	}
	return name, topics, nil
}

// buildSyllabusYAML emits a syllabus.yaml stub following docs/id-conventions.md.
// name is in the MOE official language; name_en is the English equivalent (may equal name
// when the MOE language is English, or be left blank for a human to fill in).
func buildSyllabusYAML(id, name, nameEn, countryID, description string, subjects []string) string {
	lang := countryLanguage(countryID)
	var sb strings.Builder
	sb.WriteString("id: " + id + "\n")
	sb.WriteString("name: \"" + name + "\"\n")
	sb.WriteString("name_en: \"" + nameEn + "\"\n")
	sb.WriteString("country_id: " + countryID + "\n")
	sb.WriteString("language: " + lang + "\n")
	sb.WriteString("description: \"" + description + "\"\n")
	sb.WriteString("subjects:\n")
	for _, s := range subjects {
		// subjects list holds full subject IDs: {syllabus_id}-{subject_slug}
		sb.WriteString("  - " + id + "-" + toSlug(s) + "\n")
	}
	sb.WriteString("provenance: ai-generated\n")
	sb.WriteString("generated_at: \"" + time.Now().UTC().Format(time.RFC3339) + "\"\n")
	return sb.String()
}

// buildSubjectYAML emits a subject.yaml stub following docs/id-conventions.md.
// The subject ID is grade-less (e.g. "malaysia-kssm-matematik").
func buildSubjectYAML(id, name, nameEn, syllabusID, countryID string) string {
	lang := countryLanguage(countryID)
	var sb strings.Builder
	sb.WriteString("id: " + id + "\n")
	sb.WriteString("name: \"" + name + "\"\n")
	sb.WriteString("name_en: \"" + nameEn + "\"\n")
	sb.WriteString("syllabus_id: " + syllabusID + "\n")
	sb.WriteString("country_id: " + countryID + "\n")
	sb.WriteString("language: " + lang + "\n")
	sb.WriteString("provenance: ai-generated\n")
	sb.WriteString("generated_at: \"" + time.Now().UTC().Format(time.RFC3339) + "\"\n")
	return sb.String()
}

// buildSubjectGradeYAML emits a subject-grade.yaml stub following docs/id-conventions.md.
// The subject grade ID includes the grade (e.g. "malaysia-kssm-matematik-tingkatan-3").
func buildSubjectGradeYAML(id, name, nameEn, subjectID, syllabusID, countryID string) string {
	lang := countryLanguage(countryID)
	gradeID := gradeIDFromSubjectID(id)
	var sb strings.Builder
	sb.WriteString("id: " + id + "\n")
	sb.WriteString("name: \"" + name + "\"\n")
	sb.WriteString("name_en: \"" + nameEn + "\"\n")
	sb.WriteString("subject_id: " + subjectID + "\n")
	sb.WriteString("syllabus_id: " + syllabusID + "\n")
	if gradeID != "" {
		sb.WriteString("grade_id: " + gradeID + "\n")
	}
	sb.WriteString("country_id: " + countryID + "\n")
	sb.WriteString("language: " + lang + "\n")
	sb.WriteString("provenance: ai-generated\n")
	sb.WriteString("generated_at: \"" + time.Now().UTC().Format(time.RFC3339) + "\"\n")
	return sb.String()
}

// buildTopicStubYAML emits a topic YAML stub following docs/id-conventions.md.
// name is in the MOE official language; name_en is the English equivalent.
func buildTopicStubYAML(id, name, nameEn, subjectGradeID, subjectID, syllabusID, countryID string) string {
	lang := countryLanguage(countryID)
	var sb strings.Builder
	sb.WriteString("id: " + id + "\n")
	sb.WriteString("# official_ref: \"\"  # fill in if the source document assigns a chapter/section code\n")
	sb.WriteString("name: \"" + name + "\"\n")
	sb.WriteString("name_en: \"" + nameEn + "\"\n")
	sb.WriteString("subject_grade_id: " + subjectGradeID + "\n")
	sb.WriteString("subject_id: " + subjectID + "\n")
	sb.WriteString("syllabus_id: " + syllabusID + "\n")
	sb.WriteString("country_id: " + countryID + "\n")
	sb.WriteString("language: " + lang + "\n")
	sb.WriteString("difficulty: beginner\n")
	sb.WriteString("learning_objectives: []\n")
	sb.WriteString("prerequisites:\n")
	sb.WriteString("  required: []\n")
	sb.WriteString("quality_level: 0\n")
	sb.WriteString("provenance: ai-generated\n")
	sb.WriteString("generated_at: \"" + time.Now().UTC().Format(time.RFC3339) + "\"\n")
	return sb.String()
}

// gradeIDFromSubjectID extracts the grade segment from a subject ID slug.
// It walks the parts right-to-left and returns the last word-plus-number pair it finds.
// e.g. "malaysia-kssm-matematik-tingkatan-3" → "tingkatan-3"
//
//	"india-cbse-physics-class-12"           → "class-12"
//	"uk-cambridge-igcse-mathematics-0580"   → "" (code, not a grade)
func gradeIDFromSubjectID(subjectID string) string {
	parts := strings.Split(subjectID, "-")
	for i := len(parts) - 1; i >= 1; i-- {
		p := parts[i]
		// A grade segment ends with a 1-2 digit number.
		allDigits := len(p) > 0 && len(p) <= 2
		for _, ch := range p {
			if ch < '0' || ch > '9' {
				allDigits = false
				break
			}
		}
		if allDigits {
			// The word before the number is the grade label (e.g. "tingkatan", "class", "year").
			return parts[i-1] + "-" + p
		}
	}
	return ""
}

// countryLanguage returns the BCP 47 language code for a country's MOE official language.
// Defaults to "en" for unlisted countries.
func countryLanguage(countryID string) string {
	switch countryID {
	case "malaysia":
		return "ms"
	case "indonesia":
		return "id"
	case "japan":
		return "ja"
	case "uae":
		return "ar"
	case "thailand":
		return "th"
	case "vietnam":
		return "vi"
	case "china":
		return "zh-hans"
	case "korea", "south-korea":
		return "ko"
	default:
		return "en"
	}
}

// subjectPrefix maps a subject name (any MOE language) to an English-derived
// 2-3 uppercase letter topic prefix per docs/id-conventions.md.
func subjectPrefix(name string) string {
	lower := strings.ToLower(name)
	switch {
	case containsAny(lower, "matematik", "matematika", "mathematics", "math"):
		return "MT"
	case containsAny(lower, "sains", "ilmu pengetahuan alam", "science"):
		return "SC"
	case containsAny(lower, "fizik", "fisika", "physics"):
		return "PHY"
	case containsAny(lower, "kimia", "chemistry"):
		return "CHM"
	case containsAny(lower, "biologi", "biology"):
		return "BIO"
	case containsAny(lower, "sejarah", "history"):
		return "HIS"
	case containsAny(lower, "geografi", "geography"):
		return "GEO"
	case containsAny(lower, "bahasa melayu", "bahasa indonesia", "indonesian"):
		return "BM"
	case containsAny(lower, "english"):
		return "ENG"
	case containsAny(lower, "bahasa arab", "arabic"):
		return "AR"
	default:
		// Derive 2-3 uppercase consonants from the English name.
		consonants := "bcdfghjklmnpqrstvwxyz"
		var out strings.Builder
		for _, ch := range lower {
			if strings.ContainsRune(consonants, ch) {
				out.WriteRune(ch - 32) // to uppercase
				if out.Len() == 3 {
					break
				}
			}
		}
		if out.Len() == 0 {
			return strings.ToUpper(lower[:min(2, len(lower))])
		}
		return out.String()
	}
}

func containsAny(s string, keywords ...string) bool {
	for _, kw := range keywords {
		if strings.Contains(s, kw) {
			return true
		}
	}
	return false
}

// gradeNumberFromSubjectID extracts the trailing grade number from a subject ID slug.
// e.g. "malaysia-kssm-matematik-tingkatan-3" → "3"
//
//	"india-cbse-physics-class-12" → "12"
//	"uk-cambridge-igcse-mathematics-0580" → "" (no pure grade number)
func gradeNumberFromSubjectID(subjectID string) string {
	parts := strings.Split(subjectID, "-")
	for i := len(parts) - 1; i >= 0; i-- {
		p := parts[i]
		allDigits := len(p) > 0
		for _, ch := range p {
			if ch < '0' || ch > '9' {
				allDigits = false
				break
			}
		}
		if allDigits && len(p) <= 2 {
			return p
		}
	}
	return ""
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// toSlug converts a name to a URL-safe slug.
func toSlug(name string) string {
	slug := strings.ToLower(name)
	slug = strings.ReplaceAll(slug, " ", "-")
	var out strings.Builder
	for _, ch := range slug {
		if (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '-' {
			out.WriteRune(ch)
		}
	}
	return strings.Trim(out.String(), "-")
}

// StripGradeFromName removes the grade/form/class portion from a subject name,
// returning just the subject part. It handles known MOE grade words in multiple languages.
//
//	"Matematik Tingkatan 4"  → "Matematik"
//	"Fisika Kelas 11"        → "Fisika"
//	"Physics Class 12"       → "Physics"
//	"Mathematics Form 3"     → "Mathematics"
//	"Mathematics Year 10"    → "Mathematics"
//	"Mathematics"            → "Mathematics" (no grade to strip)
func StripGradeFromName(name string) string {
	// Known grade label words (case-insensitive match).
	gradeLabels := []string{
		"tingkatan", "kelas", "class", "form", "year", "grade",
		"saff", // Arabic grade label (صف)
		"chugaku", "koko", // Japanese (中学, 高校)
	}
	words := strings.Fields(name)
	for i, w := range words {
		lower := strings.ToLower(w)
		for _, label := range gradeLabels {
			if lower == label && i+1 < len(words) {
				// Found a grade label — return everything before it, trimmed.
				result := strings.TrimSpace(strings.Join(words[:i], " "))
				if result != "" {
					return result
				}
			}
		}
	}
	return name
}

// translateToEnglish uses the AI provider to translate a name to English.
// Returns the original name unchanged if translation fails or no AI is available.
func (s *Scaffolder) translateToEnglish(ctx context.Context, name, lang string) string {
	if s.aiProvider == nil || lang == "en" || name == "" {
		return name
	}

	prompt := fmt.Sprintf(
		"Translate the following curriculum subject/topic name from %s to English.\n"+
			"Return ONLY the English translation, nothing else.\n\n%s",
		lang, name,
	)

	resp, err := s.aiProvider.Complete(ctx, ai.CompletionRequest{
		Messages: []ai.Message{{Role: "user", Content: prompt}},
	})
	if err != nil || strings.TrimSpace(resp.Content) == "" {
		return name
	}
	return strings.TrimSpace(resp.Content)
}

// translateTopicNames uses the AI provider to batch-translate topic names to English.
// Returns the original names unchanged if translation fails.
func (s *Scaffolder) translateTopicNames(ctx context.Context, topics []string, lang string) []string {
	if s.aiProvider == nil || lang == "en" || len(topics) == 0 {
		return topics
	}

	var sb strings.Builder
	for i, t := range topics {
		sb.WriteString(fmt.Sprintf("%d. %s\n", i+1, t))
	}

	prompt := fmt.Sprintf(
		"Translate the following curriculum topic names from %s to English.\n"+
			"Return ONLY the translations, one per line, numbered to match:\n\n%s",
		lang, sb.String(),
	)

	resp, err := s.aiProvider.Complete(ctx, ai.CompletionRequest{
		Messages: []ai.Message{{Role: "user", Content: prompt}},
	})
	if err != nil || strings.TrimSpace(resp.Content) == "" {
		return topics
	}

	return parseTranslatedTopics(resp.Content, topics)
}

// parseTranslatedTopics extracts translated names from AI response, falling back to originals.
func parseTranslatedTopics(response string, originals []string) []string {
	result := make([]string, len(originals))
	copy(result, originals)

	lines := strings.Split(strings.TrimSpace(response), "\n")
	idx := 0
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		// Strip leading "1. " or "1) " numbering
		for i, ch := range line {
			if ch == '.' || ch == ')' {
				line = strings.TrimSpace(line[i+1:])
				break
			}
			if ch < '0' || ch > '9' {
				break
			}
		}
		if idx < len(result) && line != "" {
			result[idx] = line
			idx++
		}
	}
	return result
}
