package generator

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/p-n-ai/oss-bot/internal/ai"
)

// ScaffoldRequest is the input for scaffolding new curriculum structures.
type ScaffoldRequest struct {
	// SyllabusID is the unique identifier for the new syllabus (e.g. "india-jee").
	SyllabusID string
	// SubjectID is the subject to scaffold within the syllabus (empty for syllabus-level).
	SubjectID string
	// SourceText is the pre-extracted content from a document, URL, or text input.
	SourceText string
	// OutputDir is the root directory to write scaffolded files into.
	OutputDir string
	// Country is used to build the directory path curricula/{country}/{syllabus_id}.
	Country string
}

// ScaffoldResult holds the files generated by the scaffolder.
type ScaffoldResult struct {
	// Files maps repo-relative paths to YAML content.
	Files map[string]string
	// Summary describes what was scaffolded.
	Summary string
}

// SyllabusYAML is a minimal syllabus descriptor.
type SyllabusYAML struct {
	ID          string   `yaml:"id"`
	Name        string   `yaml:"name"`
	Country     string   `yaml:"country"`
	Language    string   `yaml:"language"`
	Description string   `yaml:"description"`
	Subjects    []string `yaml:"subjects"`
	Provenance  string   `yaml:"provenance"`
	GeneratedAt string   `yaml:"generated_at"`
}

// Scaffolder generates new curriculum directory structures from source content.
type Scaffolder struct {
	aiProvider ai.Provider
}

// NewScaffolder creates a new Scaffolder backed by the given AI provider.
func NewScaffolder(provider ai.Provider) *Scaffolder {
	return &Scaffolder{aiProvider: provider}
}

// ScaffoldSyllabus creates a new syllabus directory with a syllabus.yaml stub.
// The AI extracts the curriculum name, subjects, and description from SourceText.
func (s *Scaffolder) ScaffoldSyllabus(ctx context.Context, req ScaffoldRequest) (*ScaffoldResult, error) {
	if req.SyllabusID == "" {
		return nil, fmt.Errorf("SyllabusID is required")
	}

	name, description, subjects, err := s.extractSyllabusInfo(ctx, req)
	if err != nil {
		// Fall back to minimal stub on AI failure
		name = req.SyllabusID
		description = "Auto-generated syllabus"
		subjects = []string{}
	}

	country := req.Country
	if country == "" {
		country = "unknown"
	}

	syllabusYAML := buildSyllabusYAML(req.SyllabusID, name, country, description, subjects)

	syllabusPath := filepath.Join("curricula", country, req.SyllabusID, "syllabus.yaml")
	files := map[string]string{syllabusPath: syllabusYAML}

	// Generate subject directory stubs
	for _, subject := range subjects {
		subjectID := toSlug(subject)
		subjectPath := filepath.Join("curricula", country, req.SyllabusID, subjectID, "subject.yaml")
		files[subjectPath] = buildSubjectYAML(subjectID, subject, req.SyllabusID)
	}

	return &ScaffoldResult{
		Files:   files,
		Summary: fmt.Sprintf("Scaffolded syllabus %q with %d subjects", req.SyllabusID, len(subjects)),
	}, nil
}

// ScaffoldSubject creates a new subject directory within an existing syllabus.
func (s *Scaffolder) ScaffoldSubject(ctx context.Context, req ScaffoldRequest) (*ScaffoldResult, error) {
	if req.SyllabusID == "" {
		return nil, fmt.Errorf("SyllabusID is required")
	}
	if req.SubjectID == "" {
		return nil, fmt.Errorf("SubjectID is required")
	}

	country := req.Country
	if country == "" {
		country = "unknown"
	}

	name, topics, err := s.extractSubjectInfo(ctx, req)
	if err != nil {
		name = req.SubjectID
		topics = []string{}
	}

	files := map[string]string{}

	// subject.yaml
	subjectPath := filepath.Join("curricula", country, req.SyllabusID, req.SubjectID, "subject.yaml")
	files[subjectPath] = buildSubjectYAML(req.SubjectID, name, req.SyllabusID)

	// topic stubs
	for i, topic := range topics {
		topicID := fmt.Sprintf("%s-%02d", strings.ToUpper(req.SubjectID[:min(2, len(req.SubjectID))]), i+1)
		topicPath := filepath.Join("curricula", country, req.SyllabusID, req.SubjectID, "topics", topicID+".yaml")
		files[topicPath] = buildTopicStubYAML(topicID, topic, req.SubjectID, req.SyllabusID)
	}

	return &ScaffoldResult{
		Files:   files,
		Summary: fmt.Sprintf("Scaffolded subject %q with %d topic stubs", req.SubjectID, len(topics)),
	}, nil
}

// WriteFiles writes all scaffolded files to the output directory.
func (s *Scaffolder) WriteFiles(result *ScaffoldResult, outputDir string) error {
	for relPath, content := range result.Files {
		full := filepath.Join(outputDir, relPath)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", relPath, err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", relPath, err)
		}
	}
	return nil
}

func (s *Scaffolder) extractSyllabusInfo(ctx context.Context, req ScaffoldRequest) (name, description string, subjects []string, err error) {
	if s.aiProvider == nil || req.SourceText == "" {
		return req.SyllabusID, "", nil, fmt.Errorf("no AI provider or source text")
	}

	prompt := fmt.Sprintf(
		"From the following curriculum document, extract:\n"+
			"1. The official name of the syllabus/curriculum\n"+
			"2. A one-sentence description\n"+
			"3. A list of subject names (one per line)\n\n"+
			"Syllabus ID: %s\n\nDocument:\n%s\n\n"+
			"Respond in this exact format:\n"+
			"NAME: <name>\nDESCRIPTION: <description>\nSUBJECTS:\n- <subject1>\n- <subject2>",
		req.SyllabusID, req.SourceText,
	)

	resp, err := s.aiProvider.Complete(ctx, ai.CompletionRequest{
		Messages: []ai.Message{{Role: "user", Content: prompt}},
	})
	if err != nil {
		return req.SyllabusID, "", nil, err
	}

	return parseSyllabusAIResponse(resp.Content, req.SyllabusID)
}

func (s *Scaffolder) extractSubjectInfo(ctx context.Context, req ScaffoldRequest) (name string, topics []string, err error) {
	if s.aiProvider == nil || req.SourceText == "" {
		return req.SubjectID, nil, fmt.Errorf("no AI provider or source text")
	}

	prompt := fmt.Sprintf(
		"From the following curriculum document, extract:\n"+
			"1. The official subject name\n"+
			"2. A list of topic names (one per line, max 20)\n\n"+
			"Subject ID: %s\nSyllabus ID: %s\n\nDocument:\n%s\n\n"+
			"Respond in this exact format:\n"+
			"NAME: <subject name>\nTOPICS:\n- <topic1>\n- <topic2>",
		req.SubjectID, req.SyllabusID, req.SourceText,
	)

	resp, err := s.aiProvider.Complete(ctx, ai.CompletionRequest{
		Messages: []ai.Message{{Role: "user", Content: prompt}},
	})
	if err != nil {
		return req.SubjectID, nil, err
	}

	return parseSubjectAIResponse(resp.Content, req.SubjectID)
}

// parseSyllabusAIResponse parses the structured AI response for syllabus info.
func parseSyllabusAIResponse(response, fallbackID string) (name, description string, subjects []string, err error) {
	name = fallbackID
	lines := strings.Split(response, "\n")
	inSubjects := false
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "NAME:") {
			name = strings.TrimSpace(strings.TrimPrefix(line, "NAME:"))
		} else if strings.HasPrefix(line, "DESCRIPTION:") {
			description = strings.TrimSpace(strings.TrimPrefix(line, "DESCRIPTION:"))
		} else if line == "SUBJECTS:" {
			inSubjects = true
		} else if inSubjects && strings.HasPrefix(line, "- ") {
			subjects = append(subjects, strings.TrimPrefix(line, "- "))
		}
	}
	return name, description, subjects, nil
}

// parseSubjectAIResponse parses the structured AI response for subject info.
func parseSubjectAIResponse(response, fallbackID string) (name string, topics []string, err error) {
	name = fallbackID
	lines := strings.Split(response, "\n")
	inTopics := false
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "NAME:") {
			name = strings.TrimSpace(strings.TrimPrefix(line, "NAME:"))
		} else if line == "TOPICS:" {
			inTopics = true
		} else if inTopics && strings.HasPrefix(line, "- ") {
			topics = append(topics, strings.TrimPrefix(line, "- "))
		}
	}
	return name, topics, nil
}

func buildSyllabusYAML(id, name, country, description string, subjects []string) string {
	var sb strings.Builder
	sb.WriteString("id: " + id + "\n")
	sb.WriteString("name: \"" + name + "\"\n")
	sb.WriteString("country: " + country + "\n")
	sb.WriteString("language: en\n")
	sb.WriteString("description: \"" + description + "\"\n")
	sb.WriteString("subjects:\n")
	for _, s := range subjects {
		sb.WriteString("  - " + toSlug(s) + "\n")
	}
	sb.WriteString("provenance: ai-generated\n")
	sb.WriteString("generated_at: \"" + time.Now().UTC().Format(time.RFC3339) + "\"\n")
	return sb.String()
}

func buildSubjectYAML(id, name, syllabusID string) string {
	var sb strings.Builder
	sb.WriteString("id: " + id + "\n")
	sb.WriteString("name: \"" + name + "\"\n")
	sb.WriteString("syllabus_id: " + syllabusID + "\n")
	sb.WriteString("provenance: ai-generated\n")
	sb.WriteString("generated_at: \"" + time.Now().UTC().Format(time.RFC3339) + "\"\n")
	return sb.String()
}

func buildTopicStubYAML(id, name, subjectID, syllabusID string) string {
	var sb strings.Builder
	sb.WriteString("id: " + id + "\n")
	sb.WriteString("name: \"" + name + "\"\n")
	sb.WriteString("subject_id: " + subjectID + "\n")
	sb.WriteString("syllabus_id: " + syllabusID + "\n")
	sb.WriteString("difficulty: beginner\n")
	sb.WriteString("learning_objectives: []\n")
	sb.WriteString("prerequisites:\n")
	sb.WriteString("  required: []\n")
	sb.WriteString("quality_level: 0\n")
	sb.WriteString("provenance: ai-generated\n")
	sb.WriteString("generated_at: \"" + time.Now().UTC().Format(time.RFC3339) + "\"\n")
	return sb.String()
}

// toSlug converts a name to a URL-safe slug.
func toSlug(name string) string {
	slug := strings.ToLower(name)
	slug = strings.ReplaceAll(slug, " ", "-")
	var out strings.Builder
	for _, ch := range slug {
		if (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '-' {
			out.WriteRune(ch)
		}
	}
	return strings.Trim(out.String(), "-")
}
